Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np

v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [11]:

b = np.random.randint(1, 11, (5, 5))
print(b)

[[ 2  7  8  8  5]
 [ 6  2  4  6  8]
 [ 6  7  4 10  5]
 [ 5  7  4  9  6]
 [ 7  4  4  7  6]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [12]:

c = np.random.random((4, 4))
print(c)

[[0.46011146 0.76338481 0.38364247 0.99731933]
 [0.98127549 0.34875875 0.53822828 0.68984784]
 [0.46824226 0.78004611 0.67029393 0.55656935]
 [0.96617458 0.16716435 0.58586404 0.31296656]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [34]:
m = np.random.randint(1, 11, (1, 5))
n = np.random.randint(1, 11, (1, 5))
print(m, n)

[[5 1 3 2 5]] [[ 4  6  3 10  2]]


In [35]:
print(m + n)
print("----------")
print(m - n)
print("----------")
print(m * n)

[[ 9  7  6 12  7]]
----------
[[ 1 -5  0 -8  3]]
----------
[[20  6  9 20 10]]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [21]:
a = np.linspace(1, 7, num=7)
b = np.linspace(7, 14, num=7)
print(a, b)
print(np.dot(a, b))

[1. 2. 3. 4. 5. 6. 7.] [ 7.          8.16666667  9.33333333 10.5        11.66666667 12.83333333
 14.        ]
326.6666666666667


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [4]:
m = np.random.randint(1, 11, (2, 2))
n = np.random.randint(1, 11, (2, 3))
print(np.dot(m, n))

[[68 80 56]
 [89 95 78]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [32]:
c = np.random.randint(1, 11, (3, 3))
print(c)
print("----------")
c_inv = np.linalg.inv(c)
print(c_inv)

[[ 1  4  9]
 [ 8  1  3]
 [10 10  1]]
----------
[[-0.04208999  0.12481858  0.00435414]
 [ 0.03193033 -0.12917271  0.10014514]
 [ 0.10159652  0.04354136 -0.04499274]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [31]:
t = np.random.random((4, 4))
print(t)
print("----------")
tt = t.T
print(tt)

[[0.46254818 0.96441034 0.60717695 0.50197464]
 [0.15648642 0.14151458 0.67945999 0.31122194]
 [0.76817891 0.24382216 0.45909595 0.15097137]
 [0.82921442 0.0572456  0.5233127  0.50871542]]
----------
[[0.46254818 0.15648642 0.76817891 0.82921442]
 [0.96441034 0.14151458 0.24382216 0.0572456 ]
 [0.60717695 0.67945999 0.45909595 0.5233127 ]
 [0.50197464 0.31122194 0.15097137 0.50871542]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [30]:

m = np.random.randint(1, 11, (3, 4))
n = np.random.randint(1, 11, (4, 1))
print(m, "\n", n)
print("----------")
print(np.dot(m, n))


[[ 6  9  3  6]
 [ 5 10 10  1]
 [ 8  5  9 10]] 
 [[7]
 [8]
 [1]
 [4]]
----------
[[141]
 [129]
 [145]]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [29]:
m = np.random.rand(2, 3)
v = np.random.rand(3)
print(m, "\n", v)
print("----------")
print(np.dot(m, v))

[[0.05847357 0.4554842  0.18154827]
 [0.31539238 0.30933607 0.82124543]] 
 [0.14895306 0.88267782 0.183162  ]
----------
[0.44400836 0.4704437 ]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [28]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))
print(m1, "\n", m2)
print("----------")
print(m1*m2)

[[9 3]
 [6 2]] 
 [[ 2  3]
 [ 6 10]]
----------
[[18  9]
 [36 20]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [27]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))
print(m1, "\n", m2)
print("----------")
print(np.dot(m1, m2))

[[5 9]
 [9 2]] 
 [[6 7]
 [3 1]]
----------
[[57 44]
 [60 65]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [26]:
h = np.random.randint(1, 101, (5, 5))
print(h)
summ = np.sum(h)
print("----------")
print(summ)

[[86 92 68 76  6]
 [ 2 70 50 40  8]
 [73 47 16 32 50]
 [93 80 12 43 31]
 [91 94 41 57 88]]
----------
1346


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [25]:
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))
print(a, "\n", b)
print("----------")
print(a - b)

[[ 1  2  6  8]
 [10  1  9  2]
 [ 5  2 10  2]
 [ 7  2  2  9]] 
 [[ 5  9  3  7]
 [ 1  3 10  4]
 [ 5  6 10  9]
 [ 1 10 10  9]]
----------
[[-4 -7  3  1]
 [ 9 -2 -1 -2]
 [ 0 -4  0 -7]
 [ 6 -8 -8  0]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [24]:
x = np.random.rand(3, 3)
print(x)

summ = np.array([sum(row) for row in x])
print("----------")
print(summ.reshape((-1, 1)))

[[0.85355733 0.41658464 0.03381375]
 [0.32228418 0.86813339 0.48906091]
 [0.0827267  0.18111995 0.66118574]]
----------
[[1.30395572]
 [1.67947849]
 [0.92503239]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [23]:
x = np.random.randint(1, 11, (3, 4))
print(x)

print("----------")
print(np.square(x))

[[ 9  2  3  5]
 [ 2 10  5  2]
 [10  5  3 10]]
----------
[[ 81   4   9  25]
 [  4 100  25   4]
 [100  25   9 100]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [39]:
r = np.random.randint(1, 51, 4)
print(r)
print("----------")
print(np.sqrt(r))

[39 10  4  8]
----------
[6.244998   3.16227766 2.         2.82842712]
